version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db
    restart: unless-stopped
    # env_file: .env
    environment:
      - MSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    # volumes:
      # - dbdata:/var/lib/mysql
    # command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1-fpm-alpine
    ports:
      - "8080:80"
    container_name: wordpress
    restart: unless-stopped
    # env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    # volumes:
      # - wordpress:/var/www/html
    networks:
      - app-network

volumes:
  db:
  wordpress:

networks:
  app-network: